developers-payu-latam/payu-latam-java-payments-sdk

src/main/java/com/payu/sdk/PayU.java
src/main/java/com/payu/sdk/model/ExtraParemeterNames.java
src/main/java/com/payu/sdk/utils/RequestUtil.java

En las transacciones tipo AUTHORIZATION_AND_CAPTURE

Se habilita el envio de los paramentros extra1, extra2 y extra3 

---

pom.xml
src/main/java/com/payu/sdk/PayU.java
src/main/java/com/payu/sdk/constants/Constants.java
src/main/java/com/payu/sdk/utils/PaymentPlanRequestUtil.java
src/test/java/com/payu/sdk/paymentplan/BankAccountApiIntegrationTest.java
src/test/java/com/payu/sdk/paymentplan/PaymentPlanApiIntegrationTest.java
src/test/java/com/payu/sdk/util/TestEnvironment.java

Se agrega la opcion de enviar el valor adicional del plan en un plan para la creación de suscripciones.

Pagosonlinepps 30183 modificar sdk pay u recibir campo valor adicional moneda sebastian gamba

---

pom.xml
src/main/java/com/payu/sdk/PayU.java
src/main/java/com/payu/sdk/model/BcashRequest.java
src/main/java/com/payu/sdk/model/Transaction.java
src/main/java/com/payu/sdk/utils/RequestUtil.java
src/main/resources/release_notes/1.1.12.txt
src/test/java/com/payu/sdk/util/UtilTest.java

[PAGOSONLINEPPS-32962](https://pagosonline.jira.com/browse/PAGOSONLINEPPS-32962) Agregar campos "bcashRequestContentType" y "bcashRequestContent"

PAGOSONLINEPPS-32962 Agregar campos "bcashRequestContentType" y "bcashRequestContent"

---

pom.xml
src/main/java/com/payu/sdk/PayU.java
src/main/java/com/payu/sdk/PayUPayments.java
src/main/java/com/payu/sdk/helper/HttpClientHelper.java
src/main/java/com/payu/sdk/model/DocumentType.java
src/main/java/com/payu/sdk/model/Order.java
src/main/java/com/payu/sdk/model/Person.java
src/main/java/com/payu/sdk/model/Transaction.java
src/main/java/com/payu/sdk/utils/RequestUtil.java
src/main/resources/release_notes/1.1.12.txt
src/main/resources/release_notes/1.1.14.txt
src/test/java/com/payu/sdk/util/UtilTest.java

Se agregan los campos para identificar el tipo de DNI del pagador, el tipo de DNI del comprador y los datos de la dirección de envío cuando se hace la solicitud de un pago de tipo AUTHORIZATION_AND_CAPTURE.

Pagosonlinepps 32880 ajustes en pagos para api bcash juan alvarez

---

pom.xml
src/main/java/com/payu/sdk/constants/Constants.java
src/main/java/com/payu/sdk/utils/SignUtil.java
src/main/resources/release_notes/1.1.16.txt
src/test/java/com/payu/sdk/util/UtilTest.java

Se crea utilitario en el SDK para la generacion de firma digital

PAGOSONLINEPPS-31410 - Utilitario para firma digital

---

pom.xml
src/main/java/com/payu/sdk/model/AbstractCardData.java
src/main/java/com/payu/sdk/model/CardType.java
src/main/java/com/payu/sdk/model/CreditCard.java
src/main/java/com/payu/sdk/model/DebitCard.java
src/main/java/com/payu/sdk/model/DebitCardAccountType.java
src/main/java/com/payu/sdk/model/Payer.java
src/main/java/com/payu/sdk/model/Transaction.java
src/main/resources/release_notes/1.1.18.txt

* Abstraer campos objeto CreditCard en AbstractCardData
* Extender clase CreditCard de clase AbstractCardData
* Crear enumeración DebitCardAccountType
* Crear clase DebitCard que extiende de AbstractCardData
* Crear enumeración CardType
* Agregar propiedad cardType a DebitCard y CreditCard
* Agregar objeto DebitCard a objeto Transaction
* Agregar propiedad gender al objeto Payer

PAGOSONLINEPPS-32264 Actualizar modelos para procesamiento de tarjetas débito y agregar género del pagador

---

pom.xml
src/main/java/com/payu/sdk/utils/RequestUtil.java
src/main/resources/release_notes/1.1.19.txt
src/test/java/com/payu/sdk/utils/RequestUtilTest.java

Add SDK authentication though parameters for PayUReports.

Pagosonlinepps 34457 multiple users raphael batista

---

pom.xml
src/main/java/com/payu/sdk/PayUPayments.java
src/main/java/com/payu/sdk/model/TransactionType.java
src/main/java/com/payu/sdk/utils/RequestUtil.java
src/main/resources/release_notes/1.1.19.txt
src/test/java/com/payu/sdk/utils/RequestUtilTest.java

Add support for partial refund.
Please, make the merge after the PR #18.

PAGOSONLINEPPS-35281

---

pom.xml
src/main/java/com/payu/sdk/PayU.java
src/main/resources/release_notes/1.2.1.txt

Ajuste del parámetro payerDniType para CODENSA

Ajuste payer dni type

---

.gitignore
pom.xml
src/main/java/com/payu/sdk/PayU.java
src/main/java/com/payu/sdk/model/Transaction.java
src/main/java/com/payu/sdk/utils/RequestUtil.java
src/main/resources/release_notes/1.2.2.txt

- Agregar nuevo campo opcional platformId a las transacciones
- Incrementar versión a 1.2.2

PAGOSONLINEPPS-37649 Agregar el id de la plataforma al SDK 

---

.gitignore
pom.xml
src/main/java/com/payu/sdk/PayUPayments.java
src/main/java/com/payu/sdk/constants/Resources.java
src/main/java/com/payu/sdk/payments/model/ConfirmationPageRequest.java
src/main/java/com/payu/sdk/utils/PaymentPlanRequestUtil.java
src/main/java/com/payu/sdk/utils/RequestUtil.java
src/main/resources/release_notes/1.2.3.txt
src/test/java/com/payu/sdk/payments/PaymentsApiIntegrationTest.java

se crea método para utilizar el envío de página de confirmación desde payments api

Se crea método para utilizar el envío de página de confirmación desde payments api

---

src/main/java/com/payu/sdk/PayU.java
src/main/java/com/payu/sdk/model/ExtraParemeterNames.java
src/main/java/com/payu/sdk/utils/RequestUtil.java
src/main/resources/release_notes/1.2.5.txt

Se realiza ajuste para enviar tag de promociones en el sdk

Se realiza ajuste para enviar tag de promociones en el sdk

---

.travis.yml
src/main/java/com/payu/sdk/model/PaymentMethodType.java
src/main/resources/release_notes/1.2.6.txt

Actualizacion de los tipos de medio de pago

actualizar los tipos de medio de pago

---

pom.xml
src/main/java/com/payu/sdk/PayUPayments.java
src/main/java/com/payu/sdk/helper/HttpClientHelper.java
src/main/resources/release_notes/1.2.6.txt

Se agregan nuevos métodos (doRefundWithRequestHeaders, doPartialRefundWithRequestHeaders) y sobrecargca de sendRequest para enviar headers extra.

PAGOSONLINEPPS-40769 Se agregan nuevos métodos y sobrecarga de sendRequest para enviar headers extra

---

pom.xml
src/main/java/com/payu/sdk/utils/RequestUtil.java
src/main/resources/release_notes/1.2.9.txt
src/test/java/com/payu/sdk/utils/RequestUtilTest.java

https://pagosonline.jira.com/browse/IOCC-109

IOCC-109 Permitir crear transacciones sobre una orden existente

---

pom.xml
src/main/java/com/payu/sdk/helper/WebClientDevWrapper.java
src/main/resources/release_notes/1.3.0.txt

Support tls1 2

---

src/main/java/com/payu/sdk/model/PaymentMethod.java
src/main/resources/release_notes/1.3.3.txt

se agrega el medio de pago BANK_REFERENCE a la enumeracion de medios de pago

La-inc-19-05-24-sdk (se agrega medio de pago Bank_Reference en payment method de SDK)

---

pom.xml
src/main/java/com/payu/sdk/model/PaymentMethod.java
src/main/resources/release_notes/1.3.4.txt

add payment method codensa

---

pom.xml
src/main/java/com/payu/sdk/PayUPayments.java
src/main/resources/release_notes/1.3.8.txt

Se remueven las validaciones para los campos PAYER_DNI_TYPE y PAYER_DNI para el medio de pago CODENSA

CNS-19 adjust document validation for codensa

---

pom.xml
src/main/java/com/payu/sdk/PayU.java
src/main/java/com/payu/sdk/PayUPayments.java
src/main/java/com/payu/sdk/payments/model/MassiveTokenPaymentsRequest.java
src/main/java/com/payu/sdk/payments/model/MassiveTokenPaymentsResponse.java
src/main/java/com/payu/sdk/utils/CommonRequestUtil.java
src/main/java/com/payu/sdk/utils/RequestUtil.java
src/main/resources/release_notes/1.3.9.txt
src/test/java/com/payu/sdk/payments/PaymentsApiIntegrationTest.java
src/test/java/com/payu/sdk/util/builders/ContentFileMother.java
src/test/java/com/payu/sdk/util/builders/MassiveTokenPaymentParametersMother.java
src/test/java/com/payu/sdk/utils/RequestUtilTest.java

Integration of massive payments with payments-api is included

feat: massive token payments included

---

pom.xml
src/main/resources/release_notes/1.3.10.txt

uploaded to version 4.3.10

---

pom.xml
src/main/java/com/payu/sdk/model/PaymentMethodType.java
src/main/resources/release_notes/1.7.0.txt

Add new payment method PSE AVANZA

Add pse avanza payment method

---

pom.xml
src/main/java/com/payu/sdk/model/PaymentMethodType.java
src/main/resources/release_notes/1.11.0.txt

Add new INTEROPERABLE_QR_BANK_TRANSFER payment method type in External SDK

Add new INTEROPERABLE_QR_BANK_TRANSFER payment method type in External SDK
